# -*- coding: utf-8 -*-
"""Leitor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TnnwsD-ru5x2MPntDJDM7iG4jQCAoNVU
"""

from joblib import load
from sklearn.linear_model import SGDClassifier
from pathlib import Path
import numpy as np
import os
 
modelo = Path(os.path.join(Path(__file__).parent.resolve(),'modelo_salvo.joblib'))
sgd_clf = load(modelo)

from matplotlib.image import imread

img_path = Path(os.path.join(Path(__file__).parent.resolve(),input('Digite o local da imagem: ')))

imagem = imread(img_path)

img = []
matrix = []
for linha in imagem:
    matrix.append([int(celula[0]) for celula in linha])

img.append(np.array(matrix))

img = [i.reshape(1, -1) for i in img]

img = np.array(img)

"""Verificando a imagem"""
print('')
if sgd_clf.predict(img[0])[0] == True:
    print('Esta imagem é um I')
else:
    print('Esta imagem não é um I')

input('\nPressione Enter para sair')